services:
  db:
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1s
      timeout: 30s
      retries: 10
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  imgpush:
    image: hauxir/imgpush
    ports:
      - "${IMAGE_PORT}:${IMAGE_PORT}"
    volumes:
      - ./images:/images

  api:
    env_file:
      - .env
    image: spring-api
    build: ./backend
    ports: 
      - "${PUBLIC_API_PORT}:${API_PORT}"


volumes:
  pgdata:
