name: Build Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change gradlew permissions
        run: chmod +x ./backend/gradlew

      - name: Build with Gradle
        run: ./backend/gradlew build -p ./backend

      # - name: Create env file
      #   run: |
      #     touch koalamarket-env.json
      #     echo "${{ secrets.POSTMAN_ENVIRONMENT }}" > koalamarket-env.json

      # - name: Setup node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "18"

      # - name: Install newman
      #   run: npm install -g newman

      # - name: Start backend service
      #   run: |
      #     nohup ./backend/gradlew bootRun -p ./backend &
      #     PID=$!
      #     echo "Spring Boot application PID: $PID" >> application.log

      # - name: Run API tests
      #   run: newman run ./koalamarket-apitests.json -e ./koalamarket-env.json

      # - name: Stop Spring Boot application
      #   run: |
      #     if [[ $(ps -p $PID | wc -l) -gt 1 ]]; then
      #       kill $PID
      #       echo "Spring Boot application stopped." >> application.log
      #     fi
