name: Build Backend

on:
  push:
    paths: 
      - 'backend/**'
      - '.github/workflows/integrate-backend.yml'
  pull_request:
    paths: 
      - "backend/**"
      - '.github/workflows/integrate-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change gradlew permissions
        run: chmod +x ./backend/gradlew

      - name: Build with Gradle
        run: ./backend/gradlew build -p ./backend

      - name: Create env file
        run: |
          touch koalamarket-env.json
          echo "${{ secrets.POSTMAN_ENVIRONMENT }}" > koalamarket-env.json

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install newman
        run: npm install -g newman

      - name: Start backend service
        run: |
          ./backend/gradlew bootRun -p ./backend &

      - name: Wait for backend to run tests
        run: |
          while [ "$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.BASE_URL }})" -ne 200 ]; do
            echo "Backend not ready yet, waiting..."
            sleep 5
          done

      #- name: Run tests
       # run: newman run ./backend/koalamarket-apitests.json --env-var="baseUrl=${{ secrets.BASE_URL }}"
